import './globals.css'
import type { Metadata } from 'next'
import Header from '@/components/Header'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

// importacion de clerk
import { ClerkProvider} from '@clerk/nextjs'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${roboto.className} grid`}>
          <Header />
          <main className='py-16'>
            {children}
          </main>
          <footer className='h-64 bg-slate-100 p-6 mt-16'>
            <ul className='list-none odd:text-slate-900 add:underline'>
              <li>Contacto</li>
              <li>Redes sociales</li>
              <li>Terminos y condiciones</li>
              <li className='text-center'>todos los derechos reservados</li>
            </ul>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  )
}
